import vinext from "vinext";
import { defineConfig } from "vite";

// macOS Seatbelt blocks FSEvents, so Codex previews need polling for HMR.
const isCodexSeatbeltSandbox = process.env.CODEX_SANDBOX === "seatbelt";

export default defineConfig(() => {
  return {
    // Vinext exposes the app directory to Vite's dependency scanner. Keep
    // declaration-only files out of the scan: Rolldown otherwise parses the
    // declarations generated by wasm-bindgen as executable TypeScript.
    optimizeDeps: {
      entries: ["app/**/*.{js,jsx,ts,tsx}", "!app/**/*.d.ts"],
    },
    server: isCodexSeatbeltSandbox
      ? { watch: { useFsEvents: false, usePolling: true } }
      : undefined,
    plugins: [vinext()],
  };
});
