/**
 * Writes the timeline as a stand-alone Three.js module (no Sim Studio runtime).
 *
 * The module holds the keyframes and the same sampling maths the editor uses
 * (linear / ease in-out / step, rotation vectors, group pivots), and can either
 * drive the nodes of the exported GLB directly (`createAnimator`) or turn the
 * keys into a regular `THREE.AnimationClip` for an `AnimationMixer`
 * (`createClip`). Nodes are found by the same names the GLB uses.
 */
import type { Keyframe } from "./animation";

export type CodeTrack = {
  node: string;
  kind: "group" | "piece";
  label: string;
  keys: Keyframe[];
};

export type CodeInput = {
  duration: number;
  loop: boolean;
  fps: number;
  tracks: CodeTrack[];
  /** Name of the GLB the module is meant to animate (for the header comment). */
  file: string;
};

const num = (value: number) => String(Math.round(value * 1e5) / 1e5);
const vec = (value: number[]) => `[${value.map(num).join(", ")}]`;

export function animationModule(input: CodeInput) {
  const data = input.tracks
    .map((track) => {
      const keys = track.keys
        .map((key) => `      { t: ${num(key.t)}, p: ${vec(key.p)}, r: ${vec(key.r)}, e: ${JSON.stringify(key.e)} },`)
        .join("\n");
      return `  {\n    node: ${JSON.stringify(track.node)}, // ${track.kind}: ${track.label.replace(/[\r\n]+/g, " ")}\n    group: ${track.kind === "group"},\n    keys: [\n${keys}\n    ],\n  },`;
    })
    .join("\n");
  return `// Generated by Sim Studio - timeline of "${input.file}".
//
//   import * as THREE from "three";
//   import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
//   import { createAnimator, createClip } from "./animation.js";
//
//   const gltf = await new GLTFLoader().loadAsync("${input.file}");
//   scene.add(gltf.scene);
//
//   // A) drive the nodes yourself (exact editor maths):
//   const animator = createAnimator(gltf.scene);
//   animator.play();
//   // render loop: animator.update(clock.getDelta());
//
//   // B) or use a regular AnimationClip:
//   const mixer = new THREE.AnimationMixer(gltf.scene);
//   mixer.clipAction(createClip(gltf.scene)).play();
//   // render loop: mixer.update(clock.getDelta());
//
// Positions are in studs (the GLB root already carries the unit scale), rotations
// are rotation vectors in degrees (axis x angle). Groups turn about their pivot
// because the group node sits on the pivot; parts keep their own rest pose.
import * as THREE from "three";

export const duration = ${num(input.duration)};
export const loop = ${input.loop};
export const fps = ${input.fps};

export const tracks = [
${data}
];

const DEG = Math.PI / 180;
const ease = (type, u) => (type === "step" ? 0 : type === "easeInOut" ? u * u * (3 - 2 * u) : u);

/** Offset (position + rotation vector) of one track at time t. */
export function sample(keys, t, out = { p: [0, 0, 0], r: [0, 0, 0] }) {
  const last = keys[keys.length - 1];
  let a = keys[0], b = keys[0], u = 0;
  if (t >= last.t) a = b = last;
  else if (t > keys[0].t) {
    let i = 0;
    while (i < keys.length - 2 && t >= keys[i + 1].t) i++;
    a = keys[i];
    b = keys[i + 1];
    const span = b.t - a.t;
    u = span > 1e-9 ? ease(a.e, (t - a.t) / span) : 1;
  }
  for (let k = 0; k < 3; k++) {
    out.p[k] = a.p[k] + (b.p[k] - a.p[k]) * u;
    out.r[k] = a.r[k] + (b.r[k] - a.r[k]) * u;
  }
  return out;
}

const rotation = (r, target) => {
  const angle = Math.hypot(r[0], r[1], r[2]);
  if (angle < 1e-9) return target.identity();
  return target.setFromAxisAngle(new THREE.Vector3(r[0] / angle, r[1] / angle, r[2] / angle), angle * DEG);
};

/** Moves the nodes of \`root\` (the loaded GLB scene) along the timeline. */
export function createAnimator(root, options = {}) {
  const targets = [];
  for (const track of tracks) {
    const node = root.getObjectByName(track.node);
    if (!node) continue;
    targets.push({
      track,
      node,
      position: node.position.clone(),
      quaternion: node.quaternion.clone(),
      pose: { p: [0, 0, 0], r: [0, 0, 0] },
      q: new THREE.Quaternion(),
    });
  }
  const state = {
    time: 0,
    speed: options.speed ?? 1,
    loop: options.loop ?? loop,
    playing: false,
    play() { state.playing = true; return state; },
    pause() { state.playing = false; return state; },
    stop() { state.playing = false; state.setTime(0); return state; },
    setTime(t) {
      state.time = Math.min(duration, Math.max(0, t));
      for (const target of targets) {
        const { pose, q, node } = target;
        sample(target.track.keys, state.time, pose);
        node.position.set(
          target.position.x + pose.p[0],
          target.position.y + pose.p[1],
          target.position.z + pose.p[2],
        );
        rotation(pose.r, q);
        // Parts compose with their own rest rotation, groups rotate about the pivot.
        if (target.track.group) node.quaternion.copy(q);
        else node.quaternion.copy(q).multiply(target.quaternion);
      }
      return state;
    },
    update(dt) {
      if (!state.playing) return state;
      let t = state.time + dt * state.speed;
      if (t >= duration) {
        if (state.loop) t %= duration;
        else { t = duration; state.playing = false; }
      }
      return state.setTime(t);
    },
  };
  state.setTime(0);
  return state;
}

/** Bakes the timeline into a THREE.AnimationClip (for an AnimationMixer). */
export function createClip(root, name = "SimStudio") {
  const clipTracks = [];
  const steps = Math.max(1, Math.ceil(duration * fps));
  for (const track of tracks) {
    const node = root.getObjectByName(track.node);
    if (!node) continue;
    const times = new Set(track.keys.map((key) => key.t));
    for (let i = 0; i <= steps; i++) times.add(Math.min(duration, (i * duration) / steps));
    const sorted = [...times].sort((a, b) => a - b);
    const positions = [], rotations = [];
    const q = new THREE.Quaternion(), previous = new THREE.Quaternion();
    const pose = { p: [0, 0, 0], r: [0, 0, 0] };
    sorted.forEach((time, index) => {
      sample(track.keys, time, pose);
      positions.push(node.position.x + pose.p[0], node.position.y + pose.p[1], node.position.z + pose.p[2]);
      rotation(pose.r, q);
      if (!track.group) q.multiply(node.quaternion);
      if (index > 0 && previous.dot(q) < 0) q.set(-q.x, -q.y, -q.z, -q.w);
      previous.copy(q);
      rotations.push(q.x, q.y, q.z, q.w);
    });
    clipTracks.push(
      new THREE.VectorKeyframeTrack(track.node + ".position", sorted, positions),
      new THREE.QuaternionKeyframeTrack(track.node + ".quaternion", sorted, rotations),
    );
  }
  return new THREE.AnimationClip(name, duration, clipTracks);
}
`;
}
